version: "3"
services:
  dapp-nest:
    image: docker.pkg.github.com/bpcrs/dapp-nest/dapp-nest:latest
    volumes:
    - ./bpcrs-network/crypto-config:/app/crypto-config
    - ./wallet:/app/wallet
    ports:
    - 6000:6000
    networks:
      - mynetwork.com
networks:
  mynetwork.com:
    external:
      name: bpcrs_byfn